version: "3.9"

services:

  backend:
    build: ./backend
    restart: always
    container_name: marinex-backend
    volumes:
      - backend_static:/app/staticfiles
      - backend_media:/app/media
    expose:
      - "8001"

  frontend:
    build: ./frontend
    restart: always
    container_name: marinex-frontend

  nginx:
    image: nginx:latest
    container_name: marinex-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - backend_static:/static
      - backend_media:/media
    depends_on:
      - backend
      - frontend

volumes:
  backend_static:
  backend_media:
