name: Deploy Marinex

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ------------------------------
    # CHECKOUT
    # ------------------------------
    - name: Checkout repository
      uses: actions/checkout@v3

    # ------------------------------
    # FRONTEND BUILD
    # ------------------------------
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20   # требуется для Vite

    - name: Build React App
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    - name: Upload Frontend to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "frontend/dist/**"
        target: "/var/www/marinex/frontend/dist"
        strip_components: 2  # обрежет frontend/dist/

    # ------------------------------
    # BACKEND DEPLOY
    # ------------------------------
    - name: Upload Django Backend to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "marinex/**"
        target: "/var/www/marinex/backend"
        strip_components: 1   # чтобы manage.py оказался прямо в backend/

    # ------------------------------
    # SERVER COMMANDS
    # ------------------------------
    - name: Install backend deps & restart services
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/marinex/backend
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
          systemctl --user restart marinex-api
          systemctl --user restart nginx
